<a href="https://colab.research.google.com/github/antonato/laboratorio3Orga/blob/master/laboratorio3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Laboratorio 3:** Simulador de Caché en un Jupyter Notebook

---





*   **Nombre:**   Antonia Arriagada
*   **Profesor**: Leonel Medina
*   **Ayudante**: Ricardo Ruz
*   **Sección**:  132810-L3
*   **Fecha**:  26-08-2020



---






## Introducción:

> La jerarquía de memoria es un concepto fundamental y necesario para entender la dinámica de la organización de computadores, donde uno de sus componentes principales recae en esta temática.  
Este trabajo se describe un simulador gráfico de 

###Objetivos:

> *   Simular el funcionamiento de una jerarquía de memoria para comparar el accesos diseño de distintas organizaciones de caché utilizando una secuencia determinada de accesos de memoria.
*   Comprender el funcionamiento de una jerarquía de memoria, la cual está compuesta de una memoria principal (RAM) y un nivel de caché, poniendo en práctica los conceptos estudiados en clases de mapeo de caché, políticas de reemplazo, métricas de rendimiento, entre otros.
*   Conocer la plataforma Colaboratory de Google, que ofrece espacio de libre acceso para desarrollar 'Jupyter Notebooks' con núcleo Python. 

## Desarrollo:


> 



In [24]:
#Importación de librerias

from google.colab import files
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


#Definición de funciones

#Salida: La lista con los numeros de relevancia en la lectura del archivo
#Proceso: Se encarga de introducir los numeros importantes del archivo de entrada en la lista
def almacenarDatos():
  print("A continuación ingrese archivo YAML con la configuración correcta:")
  uploaded = files.upload()
  for fn in uploaded.keys():
    print('User uploaded file "{name}" with length {length} bytes'.format(name=fn, length=len(uploaded[fn])))
  stringNumero = ""
  configuracion = []
  archivo = open(fn,'r')
  texto = archivo.readlines()
  for palabra in texto:
    for caracter in palabra:
      if (caracter != '\t' and caracter != '\n' and caracter.isdigit()):
        stringNumero = stringNumero + caracter
      else:
        stringNumero = stringNumero + ''
    if(len(stringNumero) != 0):
      configuracion.append(int(stringNumero))
      stringNumero = ""
  archivo.close()
  return configuracion

#Salida: Una lista con la direccion y el tipo de acceso que indica el archivo de entrada con las trazas
#Proceso: Se encarga la informacion de las trazas en una lista
def almacenarAccesosMemoria():
  print("Ingrese archivo TXT con las direcciones de memoria:")
  uploaded = files.upload()
  for fn in uploaded.keys():
    print('User uploaded file "{name}" with length {length} bytes'.format(name=fn, length=len(uploaded[fn])))
  archivo = open(fn,'r')
  accesos = []
  texto = archivo.readlines()
  separador = ','
  aux = ""
  for linea in texto:
    accesos.append(linea.split(separador))
  for lista in accesos:
    lista[0] = int(lista[0],16)
    lista[1] = str(lista[1])[1:2]
  archivo.close()
  return accesos

#Definición de constantes
configuracion = []



#Entrada: Lista de datos de la configuración de los caches
#Salida: Una lista con los datos exclusivos del cache
#Proceso: Se encarga extraer los datos del cache de una lista
def generarDataCache():
  cache = []
  configuracion.pop(0)

  for i in range(3):
    cache.append(configuracion.pop(0))
    
  return cache

In [35]:
#Definición de funciones
#Bloque Principal

print("#######################                                       #######################")
print("#######################   Bienvenido al Simulador de Caché    #######################")
print("#######################                                       #######################")
print("#####################################################################################")
print("#######################                                       #######################")
print("#######################                Entradas               #######################")
print("#######################                                       #######################")

configuracion = almacenarDatos();

#######################                                       #######################
#######################   Bienvenido al Simulador de Caché    #######################
#######################                                       #######################
#####################################################################################
#######################                                       #######################
#######################                Entradas               #######################
#######################                                       #######################
A continuación ingrese archivo YAML con la configuración correcta:


Saving config.yaml to config (12).yaml
User uploaded file "config.yaml" with length 354 bytes


In [36]:
backup = configuracion.copy()

In [3]:
accesosMemoria = almacenarAccesosMemoria()

Ingrese archivo TXT con las direcciones de memoria:


Saving dir.txt to dir.txt
User uploaded file "dir.txt" with length 128 bytes


In [4]:
print(accesosMemoria)

[[650248000, 'R'], [537133040, 'R'], [650247992, 'R'], [814425072, 'R'], [650247992, 'R'], [814425072, 'R'], [814425080, 'R'], [650248008, 'R'], [814444536, 'R'], [814425088, 'R']]


In [37]:
print("#######################                                       #######################")
print("#######################          Lectura de Datos             #######################")
print("#######################                                       #######################")

configuracion = backup.copy()

print(configuracion)

tamPalabra = configuracion.pop(0);
print("Tamaño de la palabra es: ", tamPalabra)
tamBloque = configuracion.pop(0);
print("Tamaño del bloque es: ", tamBloque)
timeMemPrincipal = configuracion.pop(-1)
print("Tiempo acceso de la Memoria Principal es: ", timeMemPrincipal)

dataCache1 = generarDataCache()
dataCache2 = generarDataCache()

if configuracion:
  dataCache3 = generarDataCache()


#######################                                       #######################
#######################          Lectura de Datos             #######################
#######################                                       #######################
[4, 16, 1, 16, 2, 1, 2, 64, 4, 10, 1000]
Tamaño de la palabra es:  4
Tamaño del bloque es:  16
Tiempo acceso de la Memoria Principal es:  1000


In [ ]:
print(cache1)
print(cache2)

[16, 2, 1]
[64, 4, 10]


In [38]:
print("     Cache 1")
print("Cantidad de bloques:    ", dataCache1[0])
print("Asociatividad:          ", dataCache1[1])
print("Tiempo de acceso:       ", dataCache1[2])

print("     Cache 2")
print("Cantidad de bloques:    ", dataCache2[0])
print("Asociatividad:          ", dataCache2[1])
print("Tiempo de acceso:       ", dataCache2[2])


     Cache 1
Cantidad de bloques:     16
Asociatividad:           2
Tiempo de acceso:        1
     Cache 2
Cantidad de bloques:     64
Asociatividad:           4
Tiempo de acceso:        10


In [8]:
%reload_ext google.colab.data_table

In [42]:
cache1 = np.zeros((16, 16)) #filas, columnas
print(cache1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [43]:
pd.DataFrame(cache1)

0    1    2    3    4    5    6   ...   9    10   11   12   13   14   15
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[16 rows x 16 columns]

## Conclusiones:


> 

